[workspace]
resolver = "2"
exclude = ["fuzz"]
members = [
  "examples/demo",
  "integration/rust",
  "pgdog",
  "pgdog-config",
  "pgdog-macros",
  "pgdog-plugin",
  "pgdog-postgres-types",
  "pgdog-stats",
  "pgdog-vector",
  "plugins/pgdog-example-plugin", "plugins/pgdog-primary-only-tables",
  "scripts/*",
]

[workspace.package]
edition = "2024"

[workspace.dependencies]
pgdog-plugin = { path = "./pgdog-plugin", version = "0.4.0", default-features = false }
pgdog-config = { path = "./pgdog-config", version = "0.1.0" }
pgdog-postgres-types = { path = "./pgdog-postgres-types"}
pg_raw_parse = { git = "https://github.com/pgdogdev/pg_raw_parse.git", rev = "89937b1" }
bon = "3.9"
derive_more = { version = "2", features = ["display", "from"] }
schemars = { version = "1.2.1", features = ["uuid1", "chrono04", "indexmap2"] }
serde_json = "1.0"
indexmap = { version = "2.14", features = ["serde"] }
serde_with = { version = "3.22", features = ["macros", "schemars_1"] }
reqwest = { version = "0.13", features = ["json"] }
bytes = "1"
uuid = { version = "1", features = ["v4", "v7", "serde"] }
parking_lot = "0.12"
futures-util = "0.3.32"

# [patch.crates-io]
# tokio = { path = "../tokio/tokio" }

# [patch."https://github.com/pgdogdev/pg_raw_parse.git"]
# pg_raw_parse = { path = "../pg_raw_parse" }

[profile.release]
lto = true
codegen-units = 1

[profile.flamegraph]
inherits = "release"
debug = true
lto = false
codegen-units = 16
