# Fork version of Bencher (Step 1 of 2)
# 
# This file is more-or-less a repeat of what we do in the main workflow for building the image
# except, now, the image gets saved as an artifact, and ran in a separate workflow.
#
# Why the separation? This allows for us to build directly on the fork, WITHOUT USING GITHUB SECRETS,
# and then have a separate workflow, that runs after this one, with privileged secrets,
# that can use the image built, and run on the main branch (mitigating any security concerns)
#
# This is the documented 2-step workflow that Bencher mentions in their docs.
name: bencher-fork-run
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  image:
    if: github.event.pull_request.head.repo.full_name != github.repository
    # This initial runner is to assemble the docker image for this PR for the Bencher runner. It doesn't run any tests itself.
    # Bencher's runners do not have outside network access; requires us to have everything ready-to-go.
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Install CI deps
        run: bash integration/ci/install-deps.sh
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: build-v1
      - name: Build
        run: cargo build --release --bin pgdog
      - name: Build image
        run: |
          docker build --build-context bin=target/release -f benches/perf/Dockerfile -t pgdog-bench .
          docker save pgdog-bench | gzip > image.tar.gz

      # Deviation from main workflow (as seen in header of this file)    
      - uses: actions/upload-artifact@v4
        with:
          name: image
          path: image.tar.gz

      # Save which PR requested the run, so the workflow running on main knows what PR to comment on
      - uses: actions/upload-artifact@v4
        with:
          name: event.json
          path: ${{ github.event_path }}
