name: fmt
on:
  push:
    branches:
      - main
      - main-ent
    paths:
      - ".github/workflows/fmt.yml"
      - "**/*.rs"
      - "integration/**"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/workflows/fmt.yml"
      - "**/*.rs"
      - "integration/**"

jobs:
  fmt:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/pgdogdev/pgdog-ci:v2
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "clippy-v1"
          shared-key: clippy
      - name: Format
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings
