name: fmt
on:
  push:
    branches:
      - main
      - main-ent
    paths:
      - "**/*.rs"
      - "integration/**"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**/*.rs"
      - "integration/**"

jobs:
  fmt:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Install CI deps
        run: bash integration/ci/install-deps.sh
      - name: Format
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings
