name: plugin-ci
on:
  push:
    branches:
      - main
      - main-ent
    paths:
      - "**/*.rs"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**/*.rs"

jobs:
  plugin-unit-tests:
    runs-on: ubuntu-24.04
    continue-on-error: true
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v6
      - name: Install CI deps
        run: bash integration/ci/install-deps.sh
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "plugin-unit-v1"
      - name: Run plugin unit tests
        run: cargo nextest run -E 'package(pgdog-example-plugin)' --no-fail-fast
