name: plugin-ci
on:
  push:
    branches:
      - main
      - main-ent
    paths:
      - ".github/workflows/plugin-ci.yml"
      - "integration/ci/**"
      - "**/*.rs"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/workflows/plugin-ci.yml"
      - "integration/ci/**"
      - "**/*.rs"

jobs:
  plugin-unit-tests:
    runs-on: ubuntu-24.04
    continue-on-error: true
    timeout-minutes: 30
    container:
      image: ghcr.io/pgdogdev/pgdog-ci:v2
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "plugin-unit-v2"
          shared-key: plugin-unit
      - name: Run plugin unit tests
        run: cargo nextest run -E 'package(pgdog-example-plugin)' --no-fail-fast
